image:
  repository: ghcr.io/abmania/whosaid-rs
  pullPolicy: IfNotPresent
  tag: main@sha256:188df2bc01a22207f347d0a8efc8d8eb5b2cfa8908b00e4375e7f85a19239786

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WHOSAID_DISCORD_TOKEN: "DISCORD_TOKEN"
            WHOSAID_DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std

          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

cnpg:
  main:
    enabled: true
    user: whosaid
    database: whosaid
