image:
  repository: ghcr.io/abmania/whosaid-rs
  pullPolicy: IfNotPresent
  tag: main@sha256:394cee3436780e493894a38314ca6b1d56e13e559754b9b179dd6b965bfd255e

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WHOSAID_DISCORD_TOKEN: "DISCORD_TOKEN"
            WHOSAID_DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

cnpg:
  main:
    enabled: true
    user: whosaid
    database: whosaid
