apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
{{- with .Values.whosaid.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}

  name: api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts:
        - "api.{{- include "whosaid.environmentUrl" . }}"
      secretName: whosaid-api-tls-{{ .Values.whosaid.env }}
  rules:
    - host: "api.{{- include "whosaid.environmentUrl" . }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
