apiVersion: v1
kind: Secret
metadata:
  name: bot-config
  namespace: {{ .Release.Namespace }}
{{- with .Values.whosaid.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}

stringData:
  token: "{{ .Values.whosaid.token }}"
