apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura
  namespace: {{ .Release.Namespace }}
{{- with .Values.whosaid.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}

spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura
  type: NodePort
