apiVersion: v1
kind: Secret
metadata:
  name: hasura-config
  namespace: {{ .Release.Namespace }}
{{- with .Values.whosaid.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}

stringData:
  uri: "postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Values.postgresql.postgresqlHost }}:{{ .Values.postgresql.postgresqlPort }}/{{- include "hasura.dbName" . }}?sslmode=require"
  username: "{{ .Values.postgresql.postgresqlUsername }}"
  password: "{{ .Values.postgresql.postgresqlPassword }}"
  host: "{{ .Values.postgresql.postgresqlHost }}"
  port: "{{ .Values.postgresql.postgresqlPort }}"
  db: "{{- include "hasura.dbName" . }}"
  maintenancedb: "{{ .Values.postgresql.postgresqlDatabase }}"
  adminSecret: "{{ .Values.hasura.adminSecret }}"
