apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
  namespace: {{ .Release.Namespace }}

{{- with .Values.whosaid.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
{{- with .Values.whosaid.annotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}

      labels:
        app: www
    spec:
{{- with .Values.whosaid.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}

      containers:
        - image: "registry.gitlab.com/mania-dev/whosaid3/www:{{ .Values.whosaid.tag }}"
          imagePullPolicy: IfNotPresent
          name: www
          env:
            - name: API_URL
              value: https://api.{{- include "whosaid.environmentUrl" . }}
            - name: GRAPHQL_URL
              value: https://hasura.{{- include "whosaid.environmentUrl" . }}/v1/graphql
            - name: CLIENT_ID
              value: {{ .Values.whosaid.client_id | quote }}
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
